services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
      - mailhog 
    links:
      - mysql
      - mailhog
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
#      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: brasil
    volumes:
      - ./.docker/mysql/:/var/lib/mysql/
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog
    ports: 
    - 1025:1025
    - 8025:8025