version: "3"
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./vhost.conf:/var/www/html/vhost.conf
    ports:
      - "80:80"
    depends_on:
      - mysql
      - mailhog 
      - rabbit            
    links:
      - mysql
      - mailhog
      - rabbit       
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
#      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: brasil
    volumes:
      - ./.docker/mysql/:/var/lib/mysql/
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog
    ports: 
    - 1025:1025
    - 8025:8025  
  rabbit:
    image: "rabbitmq:3.7.17"
    container_name: rabbit
    labels:
      NAME: "rabbit"    
    volumes:
      - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - 5672:5672
    - 15672:15672    
