version: '3'
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
        - ./src:/var/www/html
        - ./vhost.conf:/var/www/html/vhost.conf
    ports:
      - "80:80"